spring.application.name=supplyNest-file-service

server.port = 9099
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/
eureka.instance.prefer-ip-address=true

file.upload-dir=D:/SupplyNest/SupplyNest.API/supplyNest-file-service/storage/uploads