spring.application.name=supplyNest-business-service

spring.datasource.url=jdbc:postgresql://localhost:5432/supplyNest
spring.datasource.username=postgres
spring.datasource.password=880544
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port = 9096
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/